### ISSUE TITLE
Filter: Remove Cosmos DB Query

### ISSUE THREAD

**Issue by jefking** [Missing-Children-Society-Canada/messaging#14]
During the creation of the Filter Job, we needed to write a custom code to query and validate the user in the Cosmos DB; this can now be done in the binding. So this code should be removed from the 'actual' code and placed in the binding. 

> const query = 'SELECT * FROM c WHERE (c.twitter[\'$id\'] = \'' + message.userid + '\' AND \'twitter\' = \'' + message.platform + '\') OR (c.instagram[\'$id\'] = \'' + message.userid + '\' AND \'instagram\' = \'' + message.platform + '\') OR (c.facebook[\'$id\'] = \'' + message.userid + '\' AND \'facebook\' = \'' + message.platform + '\')';

By doing this, the user object should come in as a parameter for further validation.

**Comment by jefking** [comment]
@joescars this should work, as Anthony Chu unblocked this the day after we reported this issue to the team. Feel free to reach out to him, or the Functions team on this one. I tested the query and basically everything else and it should be easy. We just need to validate/test it.

**Comment by joescars** [comment]
@jefking will do. Just setting up the environment again so I can make the change and test locally.
